name: 'Container action test'
description: 'Get started with Container actions'
author: 'Kowlin'
inputs: 
  repo-token:
    description: 'Github Repository Token'
  team-name:
    description: 'A team name who's reviews will either automatically be approved or declined'
runs:
  using: 'docker'
  image: 'Dockerfile'

